# Generated by Django 4.2.30 on 2026-07-01 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='locations/')),
                ('priority', models.PositiveSmallIntegerField(default=1, help_text='Higher = visited earlier in a patrol plan.')),
                ('emergency_trigger', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plate_number', models.CharField(max_length=16, unique=True)),
                ('contact_number', models.CharField(blank=True, max_length=32)),
                ('engine_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('hybrid', 'Hybrid'), ('electric', 'Electric')], default='petrol', max_length=16)),
                ('odometer_km', models.FloatField(default=0.0)),
                ('maintenance_status', models.CharField(choices=[('healthy', 'Healthy'), ('due', 'Service Due'), ('in_service', 'In Service'), ('out_of_service', 'Out of Service')], default='healthy', max_length=16)),
                ('is_available', models.BooleanField(default=True)),
                ('current_latitude', models.FloatField(blank=True, null=True)),
                ('current_longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['plate_number'],
            },
        ),
    ]
